import { publicResult, resolveVideo } from "./resolver";
import type { ResolveResult } from "./types";
const cors = { "access-control-allow-origin": "*", "access-control-allow-methods": "GET, POST, OPTIONS", "access-control-allow-headers": "content-type, mcp-session-id", "access-control-max-age": "86400" };
const json = (value: unknown, status = 200) => new Response(JSON.stringify(value), { status, headers: { ...cors, "content-type": "application/json; charset=utf-8", "cache-control": "no-store" } });
function status(result: ResolveResult): number { return result.outcome === "invalid" ? 400 : result.outcome === "not_found" ? 404 : result.outcome === "unsupported" || result.outcome === "protected" ? 422 : result.outcome === "timeout" ? 504 : result.outcome === "ok" ? 200 : 502; }
function api(result: ResolveResult) { return result.outcome === "ok" ? { response: { status: 200, text: "OK", data: publicResult(result.data) } } : { response: { status: status(result), text: result.outcome, error: result.message } }; }
async function mcp(request: Request): Promise<Response> { let body: { method?: string; id?: string | number | null; params?: { arguments?: { url?: string } } }; try { body = await request.json(); } catch { return json({ jsonrpc: "2.0", error: { code: -32700, message: "Parse error" }, id: null }, 400); } const id = body.id ?? null;
  if (body.method === "initialize") return json({ jsonrpc: "2.0", id, result: { protocolVersion: "2025-03-26", capabilities: { tools: {} }, serverInfo: { name: "cf-stream-resolve", version: "0.1.0" } } });
  if (body.method === "tools/list") return json({ jsonrpc: "2.0", id, result: { tools: [{ name: "resolve_video", description: "Resolve a public, non-DRM MP4 or HLS video URL.", inputSchema: { type: "object", required: ["url"], properties: { url: { type: "string", format: "uri" }, format: { type: "string", enum: ["json", "redirect"] }, includeAssets: { type: "boolean" } } } }] } });
  if (body.method === "tools/call") { const result = await resolveVideo(body.params?.arguments?.url ?? ""); return json({ jsonrpc: "2.0", id, result: { content: [{ type: "text", text: JSON.stringify(api(result)) }], ...(result.outcome === "ok" ? {} : { isError: true }) } }); }
  return json({ jsonrpc: "2.0", id, error: { code: -32601, message: "Method not found" } }, 404);
}
export default { async fetch(request: Request): Promise<Response> { const url = new URL(request.url); if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: cors }); if (url.pathname === "/mcp") return request.method === "POST" ? mcp(request) : json({ error: "Use JSON-RPC 2.0 POST." }, 405);
  if (url.pathname === "/interaction/resolve.html") { const result = await resolveVideo(url.searchParams.get("url") ?? ""); return json(result.outcome === "ok" ? { url: result.data.url, label: result.data.source } : { error: result.message }, status(result)); }
  if (url.pathname !== "/") return json({ response: { status: 404, text: "not_found", error: "Unknown endpoint." } }, 404); const result = await resolveVideo(url.searchParams.get("url") ?? ""); if (result.outcome === "ok" && (url.searchParams.get("format") === "redirect" || /(?:ffprobe|libavformat)/i.test(request.headers.get("user-agent") ?? ""))) return Response.redirect(result.data.url, 307); return json(api(result), status(result));
} } satisfies ExportedHandler;
